### ISSUE TITLE
nn.parallel.data_parallel(self.cnn, input, gpu_ids) giving error

### ISSUE THREAD

**Issue by anindyasarkarIITH** [meijieru/crnn.pytorch#1]
The following error I am getting while runnunig demo.py for crnn inference.can you please help me:
```
loading pretrained model from ./data/crnn.pth
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    preds = model(image)
  File "/home/anirban/python/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anirban/crnn_inference/models/crnn.py", line 86, in forward
    conv = nn.parallel.data_parallel(self.cnn, input, gpu_ids)
  File "/home/anirban/python/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 96, in data_parallel
    output_device = device_ids[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by meijieru** [comment]
It should return immediately when `device_ids` is None.

What is your pytorch version?

**Comment by anindyasarkarIITH** [comment]
Sir,
     pytorch version is:  0.1.11_5

Regards,
Anindya

**Comment by meijieru** [comment]
It seems to be a problem from the new version. The code has been re-organized.

The document conflicts with its real implementation, so I could not fixed it immediately before we get update from official document.

For a **temporal** solution, remove multi-gpu related code, just do `model(input)`.

**Comment by daobilige-su** [comment]
I found changing gpu_ids = None into gpu_ids=[0] can fix this issue. Worked for me, FYI.

**Comment by anindyasarkarIITH** [comment]
with the only modification gpu_ids =[0] ....I am getting following error:

loading pretrained model from ./data/crnn.pth
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    preds = model(image)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py",
line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anindya/Projects/crnn_inference/models/crnn.py", line 88, in
forward
    conv = nn.parallel.data_parallel(self.cnn, input, gpu_ids)
  File
"/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py",
line 100, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py",
line 206, in __call__
    result = self.forward(*input, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py",
line 64, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py",
line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py",
line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py",
line 39, in conv2d
    return f(input, weight, bias)
RuntimeError: tensors are on different GPUs

**Comment by daobilige-su** [comment]
You are getting a runtime error, "tensors are on different GPUs".
Do you have multiple GPU on your machine? 
Anyway, in my case, I have only one GPU on my laptop, there everything works after making that only change.

**Comment by anindyasarkarIITH** [comment]
I have also only one GPU on my laptop...
can you send me the modified code?
 I am using cuda 8.0 ..
what is your cuda version?

**Comment by daobilige-su** [comment]
Then, it is interesting. I also installed CUDA 8.0 with cudnn 5.1.
Is it possible that your default GPU id is not 0?
Anyway, "crnn.py" is the only file I have changed and it is attached with
this mail.
Hope it helps.



Daobilige Su

PostDoc Research Associate

Australian Centre for Filed Robotics (ACFR) <http://www.acfr.usyd.edu.au/>,
Faculty of Engineering and IT (FEIT),
University of Sydney <https://sydney.edu.au/>,
Australia

Phone: +61 (0)2 <http://%20+61%202%209514%202967/>9351 3283
<http://%20+61%202%209514%202967/>
Mobile: +61 410 891 777 <http://+61+410+891+777/>
Email: d.su [AT] acfr.usyd.edu.au
Web: sites.google.com/site/daobiligesu/ （concise version）
        http://daobilige-su.github.io/ (feature rich version)
<http://sites.google.com/site/daobiligesu/>

On Tue, Apr 4, 2017 at 12:19 AM, anindyasarkarIITH <notifications@github.com

**Comment by daobilige-su** [comment]
Looks github not support attachments. So the crnn.py file is copy pasted below.
---
import torch.nn as nn
import torch.nn.parallel


class BidirectionalLSTM(nn.Module):

    def __init__(self, nIn, nHidden, nOut, ngpu):
        super(BidirectionalLSTM, self).__init__()
        self.ngpu = ngpu

        self.rnn = nn.LSTM(nIn, nHidden, bidirectional=True)
        self.embedding = nn.Linear(nHidden * 2, nOut)

    def forward(self, input):
        # gpu_ids = None
        gpu_ids = [0]
        if isinstance(input.data, torch.cuda.FloatTensor) and self.ngpu > 1:
            gpu_ids = range(self.ngpu)
        recurrent, _ = nn.parallel.data_parallel(
            self.rnn, input, gpu_ids)  # [T, b, h * 2]

        T, b, h = recurrent.size()
        t_rec = recurrent.view(T * b, h)
        output = nn.parallel.data_parallel(
            self.embedding, t_rec, gpu_ids)  # [T * b, nOut]
        output = output.view(T, b, -1)

        return output


class CRNN(nn.Module):

    def __init__(self, imgH, nc, nclass, nh, ngpu, n_rnn=2, leakyRelu=False):
        super(CRNN, self).__init__()
        self.ngpu = ngpu
        assert imgH % 16 == 0, 'imgH has to be a multiple of 16'

        ks = [3, 3, 3, 3, 3, 3, 2]
        ps = [1, 1, 1, 1, 1, 1, 0]
        ss = [1, 1, 1, 1, 1, 1, 1]
        nm = [64, 128, 256, 256, 512, 512, 512]

        cnn = nn.Sequential()

        def convRelu(i, batchNormalization=False):
            nIn = nc if i == 0 else nm[i - 1]
            nOut = nm[i]
            cnn.add_module('conv{0}'.format(i),
                           nn.Conv2d(nIn, nOut, ks[i], ss[i], ps[i]))
            if batchNormalization:
                cnn.add_module('batchnorm{0}'.format(i), nn.BatchNorm2d(nOut))
            if leakyRelu:
                cnn.add_module('relu{0}'.format(i),
                               nn.LeakyReLU(0.2, inplace=True))
            else:
                cnn.add_module('relu{0}'.format(i), nn.ReLU(True))

        convRelu(0)
        cnn.add_module('pooling{0}'.format(0), nn.MaxPool2d(2, 2))  # 64x16x64
        convRelu(1)
        cnn.add_module('pooling{0}'.format(1), nn.MaxPool2d(2, 2))  # 128x8x32
        convRelu(2, True)
        convRelu(3)
        cnn.add_module('pooling{0}'.format(2), nn.MaxPool2d((2, 2),
                                                            (2, 1),
                                                            (0, 1)))  # 256x4x16
        convRelu(4, True)
        convRelu(5)
        cnn.add_module('pooling{0}'.format(3), nn.MaxPool2d((2, 2),
                                                            (2, 1),
                                                            (0, 1)))  # 512x2x16
        convRelu(6, True)  # 512x1x16

        self.cnn = cnn
        self.rnn = nn.Sequential(
            BidirectionalLSTM(512, nh, nh, ngpu),
            BidirectionalLSTM(nh, nh, nclass, ngpu)
        )

    def forward(self, input):
        # gpu_ids = None
        gpu_ids = [0]
        if isinstance(input.data, torch.cuda.FloatTensor) and self.ngpu > 1:
            gpu_ids = range(self.ngpu)

        # conv features
        conv = nn.parallel.data_parallel(self.cnn, input, gpu_ids)
        b, c, h, w = conv.size()
        assert h == 1, "the height of conv must be 1"
        conv = conv.squeeze(2)
        conv = conv.permute(2, 0, 1)  # [w, b, c]

        # rnn features
        output = nn.parallel.data_parallel(self.rnn, conv, gpu_ids)

        return output
---

**Comment by meijieru** [comment]
Solved by [commit](https://github.com/meijieru/crnn.pytorch/commit/1cd71dffce8545efa7c559ed40358496e270e724)

**Comment by ahmedmazari** [comment]
thank you  @daobilige-su  l solved my problem here https://github.com/meijieru/crnn.pytorch/issues/9 using your code
