### ISSUE TITLE
Issues related to  dataset.resizeNormalize((100, 32))

### ISSUE THREAD

**Issue by ahmedmazari** [meijieru/crnn.pytorch#10]
Hello,
l noticed that all the images are constrained to be in the same size. 
1- `transformer = dataset.resizeNormalize((100, 32)) `in `demo.py`
img_path = '/demo.png' of the sequence "available" has a dimension of  (184,72), when we rescale it to (100,32) the amount of lost information is negligible. But when we have images of variable sizes far from 100 and 32 this will be problematic. In this case how did you solve the problem.

2- the same question than the one asked in (1-) `transform=dataset.resizeNormalize((128, 32)))` in  `crnn_main.py`. Why we should resize all the images to (128,32) ?
for the height=32 l do agree because it allows to make difference for example between 'i' and 'l' so the height is important to discriminate between characters, but for the width=128 l don't understand why it should be! 

3- Does the parameters `transform=dataset.resizeNormalize((128, 32)))` in  `crnn_main.py` should remain statics to (128,32) to be able to use the architecture or can be changed to the dimensions which fit our data ?

**Comment by meijieru** [comment]
1. It's just a design choice. You could adjust the image height, however at the same time, you will have to modify the architecture to ensure the input to LSTM has height 1.
2. The pretrained model is converted from origin one which trained on (100, 32) images.
2. It's a mistake, (100, 32) will be the best for matching when tested.

**Comment by ahmedmazari** [comment]
@meijieru thank you

**Comment by ahmedmazari-dhatim** [comment]
@meijieru in `crnn_main.py`   we have
```
test_dataset = dataset.lmdbDataset(
    root=opt.valroot, transform=dataset.resizeNormalize((100, 32)))
```

Does it mean that the model accept only images of height=32 and width=100.  For each input image , regardless of it height and width they are all resized to (100,32).
1) In other way this architecture can only works with images of (100,32) ?
2) What if we keep the width variable all the time or fix it to another value ?
3) Why exactly the architecture is designed for images with height=32 is it mathematically grounded or it is related the nature of dataset ?

Thank you

**Comment by meijieru** [comment]
1. All images with width 32.
2. It will raise a runtime error.
3. It is just a design choice (work well enough).

**Comment by ahmedmazari-dhatim** [comment]
@meijieru 
1. not only images height=32 but also width=100 in this case

**Comment by meijieru** [comment]
It is just for convenience.
