### ISSUE TITLE
code details in crnn_main.py

### ISSUE THREAD

**Issue by anonymous2792** [meijieru/crnn.pytorch#104]
Hi Meijieru,

I am new to pyTorch.
Can you kindly describe the line 97 in crnn_main.py which is:

``image = torch.FloatTensor(opt.batchSize, 3, opt.imgH, opt.imgH)``

Why does this initialization contains two time ``opt.imgH``, and does not care for ``opt.imgW``?

**Comment by meijieru** [comment]
This line is just to declare the variable, the shape or value of it could be any value.

**Comment by anonymous2792** [comment]
Thanks for the information
