### ISSUE TITLE
convert the torch model to the pytorch model

### ISSUE THREAD

**Issue by angel1288** [meijieru/crnn.pytorch#105]
@meijieru 
I tried to convert the torch _.t7_ model to the pytorch _.pth_ model, but It occurred the following errors：（the model.t7 belongs to crnn）
`$ python convert_t7.py -m model.t7`
Traceback (most recent call last):
  File "convert_t7.py", line 167, in <module>
    torch_to_pytorch(py_model, args.model_file, args.output)
  File "convert_t7.py", line 129, in torch_to_pytorch
    t7_name = t7_layer[0].split('.')[-1]
**AttributeError: 'int' object has no attribute 'split'**

Why? Thank you!

**Comment by meijieru** [comment]
#32

**Comment by angel1288** [comment]
@meijieru OK! Thank you! But I add the following code to the end of _convert_t7.lua_. 
`saveModel('/路径/model.t7', '/同一路径/model_new.t7')`
It occurred the following errors：
```
/opt/torch/install/bin/luajit: convert_t7.lua:54: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	convert_t7.lua:54: in function 'modelToList'
	convert_t7.lua:87: in function 'saveModel'
	convert_t7.lua:91: in main chunk
	[C]: in function 'dofile'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```
Why? Thank you!

**Comment by angel1288** [comment]
@meijieru Hello！Now I have no way to train model like #32 (rayush7 said). Any idea on how to resolve this problem? Thank you!

**Comment by angel1288** [comment]
@meijieru `for i, layer in pairs(model.modules) do` 
 model.modules is nil. 
Why? Thank you!

**Comment by angel1288** [comment]
@meijieru Hello! How did you convert successfully? Thank you!

**Comment by angel1288** [comment]
@meijieru The type of the parameter _model_ is _string_. So _model.modules_ is nil. How did you execute the code？Thank you!

**Comment by angel1288** [comment]
@meijieru Ok! Thank you！ According to what @rayush7 said, I encounters the following error:
```
       -1.41769660e+00,  3.03534605e-02, -5.62128186e-01, -1.07657135e+00,
       -1.16623843e+00,  1.19312778e-02, -9.57154751e-01, -4.30558957e-02,
        2.00892948e-02, -2.61077076e-01, -1.33102310e+00, -7.00862765e-01,
       -1.26928639e+00, -9.80621397e-01, -1.20615649e+00, -6.30395472e-01,
       -1.05960980e-01, -1.92593560e-01, -1.00499845e+00, -2.04740256e-01,
       -6.66820526e-01, -1.50630307e+00, -2.83935126e-02, -1.21593153e+00,
       -5.75820267e-01, -1.11435843e+00, -9.92438495e-01, -9.83581901e-01,
       -1.20660889e+00, -1.09310710e+00, -8.35404754e-01,  6.65640645e-03,
       -9.16727543e-01, -2.48603552e-04, -1.00986338e+00, -9.20418441e-01,
       -1.38244843e+00, -2.36728132e-01, -3.98191482e-01, -5.29985905e-01],
      dtype=float32)]], [b'cudnn.ReLU', []]]]
Traceback (most recent call last):
  File "convert_t7.py", line 168, in <module>
    torch_to_pytorch(py_model, args.model_file, args.output)
  File "convert_t7.py", line 130, in torch_to_pytorch
    t7_name = t7_layer[0].split('.')[-1]
TypeError: a bytes-like object is required, not 'str'
```
Why? Thank you!

**Comment by angel1288** [comment]
@meijieru I have resolved the last problem. The below lines have been modified: _line 88_ and _line 129_,
modify ` t7_layer[0]` to `bytes.decode(t7_layer[0])]`.

- But when saving, it occurred the following error:    
 **torch.save(model.state_dict(), output)**
```
Traceback (most recent call last):
  File "convert_t7.py", line 167, in <module>
    torch_to_pytorch(py_model, args.model_file, args.output)
  File "convert_t7.py", line 143, in torch_to_pytorch
    **torch.save(model.state_dict(), output)**
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 117, in _with_file_like
    return body(f)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 135, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 193, in _save
    pickle_module.dump(MAGIC_NUMBER, f, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute
```
- _line 143_  `torch.save(model.state_dict(), output)` ? :  _model.state_dict()_ 
- Why? Thank you!

**Comment by angel1288** [comment]
@meijieru `convert_t7.py` ：` torch_to_pytorch(model, t7_file, output)`

- Due to **model**.state_dict() in  _line 143_ `torch.save(model.state_dict(), output)`  , `line 116~line 141` are equivalent to no work.
- Is there anything wrong with `convert_t7.py`?
- Thank you!

**Comment by angel1288** [comment]
@meijieru I have resolve the last problem. The reason is no output file.

**Comment by ibrahimsoliman97** [comment]
Hi @angel1288 ,

May i know how you solve the problem of 

> Traceback (most recent call last):
  File "convert_t7.py", line 167, in <module>
    torch_to_pytorch(py_model, args.model_file, args.output)
  File "convert_t7.py", line 131, in torch_to_pytorch
    raise RuntimeError('%s does not match %s' % (py_name, t7_name))
RuntimeError: Conv2d does not match Sequential

i am facing the same problem after i edited the bytes.decode(t7_layer[0]) at line 88 and 129.

Thank you!!

**Comment by uzl** [comment]
for me it worked!  
1. convert into a new `.t7` from _original lua weight `.t7`_  using `convert_t7.lua` 
2. now convert into `.pth` from newly generated `.t7` (use python version **2.7**)
