### ISSUE TITLE
多ＧＰＵ　

### ISSUE THREAD

**Issue by CXY573** [meijieru/crnn.pytorch#109]
你好，我在本地主机跑只有一个ＧＰＵ这是没有问题的，但是由于速度太慢我想放在服务器上跑，服务器上是四块ＧＰＵ，但是即使我没有没有做任何修改
python crnn_main.py --trainroot train --valroot train --cuda
仅仅这样运行　也会出现如下错误
AttributeError: 'module' object has no attribute 'gpu_ctc'
我并没有尝试使用多块ＧＰＵ，所以我没有设置ｎｇｐｕ参数，如上我把－－ｃｕｄａ取消掉　会提示我没有使用ｃｕｄａ，程序是可以用ｃｐｕ运行的

这个需要怎么解决？

**Comment by meijieru** [comment]
请先在已有的issue中寻找解决方案，谢谢
