### ISSUE TITLE
crnn收敛问题

### ISSUE THREAD

**Issue by ccnankai** [meijieru/crnn.pytorch#116]
@meijieru 
我的样本只有数字和小写字母，请问为什么损失函数不下降呢？  数据集用creat_dataset制作的

![2018-04-18 1 21 41](https://user-images.githubusercontent.com/33537489/38913188-0474373a-430c-11e8-9e2c-ed66b0102620.png)

**Comment by meijieru** [comment]
关于这方面的issue已经非常多了，请不要再开 ，谢谢

**Comment by ccnankai** [comment]
@meijieru   都删了
