### ISSUE TITLE
使用CTPN检测到的文本是连续的（不是一个单词）正确的做法是？

### ISSUE THREAD

**Issue by atVoidYX** [meijieru/crnn.pytorch#122]
您好，想向您请教个问题，我使用文本检测算法（比如CTPN）定位到文本位置然后提取。
但是一般是一个句子。这时候正确的作法应该是什么？
我只是比较简单的想到将句子再分割成单个图片再输入到CRNN。
您觉得这个问题应该怎么解决？

**Comment by meijieru** [comment]
这个方法不太适合做句子的识别的，最好换个算法。或者先把句子的图片切成词的图片

**Comment by liangshuang1993** [comment]
@atVoidYX 你好，我也遇到了这个问题，请问你是分割句子，还是换了其他方法呢？谢谢！
