### ISSUE TITLE
RuntimeError: cublas runtime error : an internal operation failed at /pytorch/torch/lib/THC/THCBlas.cu:246

### ISSUE THREAD

**Issue by xiaoyunyu** [meijieru/crnn.pytorch#125]
请问这个问题怎么解决？
`Traceback (most recent call last):
  File "crnn_main.py", line 211, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 196, in trainBatch
    cost.backward()
  File "/srv/sfw/anaconda/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/srv/sfw/anaconda/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cublas runtime error : an internal operation failed at /pytorch/torch/lib/THC/THCBlas.cu:246
Exception KeyError: KeyError(<weakref at 0x7fcccda632b8; to 'tqdm' at 0x7fcccd0f2d90>,) in <bound method tqdm.__del__ of   0%|                                                         | 0/2490 [00:01<?, ?it/s]> ignored
`
我的python版本2.7，pytorch版本0.3.0，CUDA8.0，cudnn6.0
希望能告知可以跑通的版本。。不胜感激！！

**Comment by meijieru** [comment]
更像是pytorch相关的问题，可以去论坛问一下

**Comment by saikrishnarallabandi** [comment]
Good answer dude

**Comment by lijian-1994** [comment]
@xiaoyunyu 我也遇到了相同的问题，请问你是如何解决的？谢谢！
