### ISSUE TITLE
no CUDA-capable device is detected 问题请教

### ISSUE THREAD

**Issue by devshilei** [meijieru/crnn.pytorch#137]
运行crnn_main.py文件报错：
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCGeneral.cpp:70

请大神解答。谢谢。

**Comment by leonzhu211** [comment]
建议先试运行一下 pytorch tutorial 中简单的 case。
感觉这个问题与 crnn 无关，应该是环境问题。

**Comment by lfang-salk** [comment]
You may refer to this post.
https://github.com/pytorch/pytorch/issues/5046
