### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'data_parallel'

### ISSUE THREAD

**Issue by rohitgajawada** [meijieru/crnn.pytorch#14]
Hi! When I was trying your demo program, I got this error:

loading pretrained model from ./data/crnn.pth
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    preds = model(image)
  File "/home/rohit/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rohit/Documents/gitprojects/crnn.pytorch/models/crnn.py", line 78, in forward
    conv = utils.data_parallel(self.cnn, input, self.ngpu)
AttributeError: module 'utils' has no attribute 'data_parallel'

Could you please tell me how I can fix this?

**Comment by meijieru** [comment]
I could not re-produce this problem.
You could just put this function in `crnn.py`.

**Comment by rohitgajawada** [comment]
Thank you, that solved it :D

**Comment by anguoyang** [comment]
hi @rohitgajawada ,  i faced the same problem, could you please share me some ideas on how to solve this problem? thank you.
i have checked the source code, there is no data_parallel function, pytorch.torch.nn has this function, however, when called this function, an error occured:
    output_device = device_ids[0]
TypeError: 'int' object is not subscriptable

**Comment by chaser1** [comment]
You may have implemented  function data_parallel in  utils, but utils is a third-party library, modify the file name or put this function in crnn.py.
