### ISSUE TITLE
ctc loss 经常出现 inf

### ISSUE THREAD

**Issue by leonzhu211** [meijieru/crnn.pytorch#140]
@meijieru 
请教关于 ctc loss 出现 inf 的原因。

我用 py 生成测试数据，大概逻辑是
1. 选一张背景图片
2. 选一句中文字符串，截定长 5 个字符，得到 label
3. 计算该字符串的 w,h，画到背景图片上，再裁剪，得到 img

MyDataset  的 getitem 返回的是  img, label
alphabet 为所有 gbk 中文字符 list(set(gbk_arr))，长度比较大

导致模型最后是
  (rnn): Sequential(
    (0): BidirectionalLSTM(
      (rnn): LSTM(512, 256, bidirectional=True)
      (embedding): Linear(in_features=512, out_features=256, bias=True)
    )
    (1): BidirectionalLSTM(
      (rnn): LSTM(256, 256, bidirectional=True)
      (embedding): Linear(in_features=512, out_features=7522, bias=True)
    )
  )

batch size 为 8

但 ctc loss 经常出现 inf

loss 正常有值
_CTC:: torch.Size([8]) tensor([ 172.6843,  117.1932,  162.0956,   72.6978,  161.8735,  124.5285,
         199.0926,  119.1346]) tensor(1129.3000)
averager:: add: 1 tensor(141.1625)
[0/25][265/118649] Loss: 141.162506

loss 为 inf
_CTC:: torch.Size([8]) tensor([      inf,  162.1736,  242.1988,  140.1967,  237.5101,  147.4658,
         145.6334,  100.1794]) tensor(inf.)
averager:: add: 1 tensor(inf.)
[0/25][266/118649] Loss: inf

case 的打印
s:  赵薇林心, w: 291, h: 64, font_size: 68
s: 说出你的故, w: 186, h: 35, font_size: 37
s: 等到救援队, w: 315, h: 63, font_size: 63
s: 窜？还是曾, w: 310, h: 60, font_size: 62
s: 大群自强不, w: 210, h: 41, font_size: 42
s: 国家力量步, w: 495, h: 97, font_size: 99
s: 探员罗根在, w: 445, h: 84, font_size: 89
s: 莱坞当红小, w: 375, h: 76, font_size: 75

想问下
1. 这样做 dataset 是对的吗？
2. ctc loss 出现 inf 的原因是什么？

谢谢!

**Comment by leonzhu211** [comment]
看起来是 lr 太大的原因。改为 --lr=0.0005 没出现了

**Comment by Tangent-Wei** [comment]
请问你中文字符集多大规模呢？我用300个中文来训练，当batch size>2的时候就会报out of memory的错误，P40 GPU内存20多GB

**Comment by leonzhu211** [comment]
我用 5k+ 的汉字，运行正常。

**Comment by Aurora11111** [comment]
@leonzhu211 请问你的数据集是用什么生成的,我的数据集在crnn_main.py里面一直报Corrupted image for

**Comment by leonzhu211** [comment]
@Aurora11111 搜狗有个新闻语料库。我另外找了一些图片，随机用了一些字体。
文本+图片+字体，随机组合，生成了自己的数据集

**Comment by Aurora11111** [comment]
@leonzhu211  thanks

**Comment by RobertXiaobinW** [comment]
> 看起来是 lr 太大的原因。改为 --lr=0.0005 没出现了

可是我调成0.000005了，还是会inf，而且是从一开始就inf，是什么原因呢？我是在预训练模型的基础上进行训练的
