### ISSUE TITLE
train on custom dataset

### ISSUE THREAD

**Issue by zeynali** [meijieru/crnn.pytorch#148]
Hi ,
Thanks for your sharing this codes. i want to recognize the characters of car plates for Persian language.
and i gathered a lot of images for this but i don't know, How do i include the labels?please put a example both image and its related label for training.
Please specify the data (image and label) structure for training. such this : 

---dataset
---------images
----------------1.jpg
----------------2.jpg
----------------3.jpg

---------labels
------------( i don't know what should be)

**Comment by meijieru** [comment]
See `create_dataset.py` in origin respository.
