### ISSUE TITLE
AssertionError: the height of conv must be 1

### ISSUE THREAD

**Issue by abhiML** [meijieru/crnn.pytorch#18]
I keep getting this error on running crnn_main.py.\
`Traceback (most recent call last):
  File "crnn_main.py", line 200, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 183, in trainBatch
    preds = crnn(image)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/crnn.pytorch/models/crnn.py", line 80, in forward
    assert h == 1, "the height of conv must be 1"
AssertionError: the height of conv must be 1
`

**Comment by meijieru** [comment]
The height of images must be 32 for this assesrtion.

**Comment by ahmedmazari-dhatim** [comment]
@meijieru , so we need to rescale our dataset to height=32 before running cnn_main.py ?

**Comment by abhiML** [comment]
@ahmedmazari-dhatim  yeah I have started the resizing to 100x32. What about you?

**Comment by meijieru** [comment]
@ahmedmazari-dhatim  yes

**Comment by abhiML** [comment]
@ahmedmazari-dhatim  how are you resizing it? I modified the create_dataset.py file and inserted these three lines 
`img=Image.open(imagePath,'r')
img=img.resize((100,32),Image.ANTIALIAS)
img.save(imagePath)
`

I am still getting the same error

**Comment by abhiML** [comment]
@meijieru  Even after resizing all the images to 100x32 I am getting the same error.

**Comment by meijieru** [comment]
Please check parameters in `crnn_main.py` in detail.

**Comment by ahmedmazari-dhatim** [comment]
@abhiML  you just need to rescale the height, the width variable size is accepted.  But after resizing also to (100,32) l get the same error

**Comment by ahmedmazari-dhatim** [comment]
@abhiML , you don't get the same error, change the following lines in dataset.py 
line 95 and 100:
`torch.range`  to `torch.arange`

and run again your code . please let me know

**Comment by abhiML** [comment]
I think you gotta give imgH=32 in the parameters while running the crnn_main.py

**Comment by ahmedmazari-dhatim** [comment]
haaa , l was about to share the answer. Yes definitely it works . @abhiML  do you mind give me your email ?

**Comment by abhiML** [comment]
abhi.phy95@gmail.com

**Comment by abhiML** [comment]
tell me when u see it. Ill delete

**Comment by ahmedmazari-dhatim** [comment]
Thanks it's done
