### ISSUE TITLE
torch.FloatTensor(opt.batchSize, 3, opt.imgH, opt.imgH) in crnn_main.py

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [meijieru/crnn.pytorch#20]
Hello,
l stack at the following line code in  `crnn_main.py`

1. in line 100
`image = torch.FloatTensor(opt.batchSize, 3, opt.imgH, opt.imgH)`
we are are supposed to have `imgH, imgW` or you rescale the image to be symmetric 32 * 32 ?

2. line 188 
`cost.backward()`
How it backward the cost ?

3. in line 101
`text = torch.IntTensor(opt.batchSize * 5) `
Why is it batchSize*5? is 5 a static parameter or can be changed ?

**Comment by meijieru** [comment]
1. The shape of these variable would be changed according to the true images and labels.
2. It's a universal interface provided by PyTorch.
3. As 1

Please read the code carefully before open a issue. Thanks.

**Comment by abhiML** [comment]
@meijieru I have input of 100 x 32. So by this line am I rescaling the image to 32x32?

**Comment by meijieru** [comment]
This is only in order to create `imagev`. You do not really resize the image.

**Comment by abhiML** [comment]
So what is the logic behind giving the width and height both as imgH?

**Comment by meijieru** [comment]
It has no meaning.
