### ISSUE TITLE
ImportError:No module named _warp_ctc

### ISSUE THREAD

**Issue by GA-17a** [meijieru/crnn.pytorch#200]
Hi: @meijieru 
 I meet a question,and maybe I need your help.  
 I have download 'warp_ctc_pytorch' from http://github.com/SeanNaren/warp-ctc ,and I have utilized the files in pytorch_blinding.While when I try to run the train.py ,it still tells me "ImportError:No module named _warp_ctc".
      It happened when the file _ _  _init_ _ _.py   under the folder "warpctc_pytorch" run to "from ._warp_ctc import *" ,is some files missed?And does anybody meet the same question?How did you resolve it?
      looking for your reply!Thanks!

**Comment by SreenijaK** [comment]
how did you solve this issue?

**Comment by happy20200** [comment]
did you solve this problem?i meet the same

**Comment by Yasin40** [comment]
> did you solve this problem?i meet the same

me too.
