### ISSUE TITLE
【劝退】大家不要在这里浪费时间了，这套代码bug 太多，也没有人维护。

### ISSUE THREAD

**Issue by allenxcp** [meijieru/crnn.pytorch#220]
【劝退】大家不要在这里浪费时间了，这套代码bug 太多，也没有人维护。

**Comment by HandsomeHans** [comment]
还好吧，我调试成功，已经能正常训练和测试了。

**Comment by zcswdt** [comment]
> 还好吧，我调试成功，已经能正常训练和测试了。

您好，您的模型训练出来了吗？效果怎么样，我有些问题请教你

**Comment by HandsomeHans** [comment]
@zcswdt 训练出来啦，你请说。

**Comment by allenxcp** [comment]
推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec

**Comment by zcswdt** [comment]
> @zcswdt 训练出来啦，你请说。

谢谢回复，可以留个联系方式我请教你几个问题吗？谢谢。

**Comment by zcswdt** [comment]
> 推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec

谢谢回复，我也用了这个，但是有问题啊，我自己合成300万的280*32定长十字的图片，但是训练出来的模型，在测试集里面表现效果好，测试图片高度宽度大小不和生成的图片一致或者是出入太大的时候就识别错误，请问这样有什么好的解决方法？

**Comment by HandsomeHans** [comment]
> > 推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec
> 
> 谢谢回复，我也用了这个，但是有问题啊，我自己合成300万的280*32定长十字的图片，但是训练出来的模型，在测试集里面表现效果好，测试图片高度宽度大小不和生成的图片一致或者是出入太大的时候就识别错误，请问这样有什么好的解决方法？

这个问题说明是模型泛化性不好。测试的时候，首先高度一定要32；其次你训练数据集是自己生成的，应该是复杂度不够，太单调了，所以你在测试集上有效果，在其他非测试集图片上效果就不行了。给你的建议是用公开数据集，或者把你的数据集和公开的数据集混合起来重新训练，并且生成数据和公开数据比例不能差太大。

**Comment by yuxiaomu** [comment]
> @zcswdt 训练出来啦，你请说。



> 还好吧，我调试成功，已经能正常训练和测试了。

您好，看到您已经调试出来了，所以很突兀的就过来问你，请问您知道我这个是怎么回事吗
![image](https://user-images.githubusercontent.com/47933430/82774668-11caf800-9e78-11ea-96cd-509cff015268.png)

**Comment by FortuneSeeker** [comment]
> 还好吧，我调试成功，已经能正常训练和测试了。

你好，请问在训练的时候有碰到过这个问题吗：
Traceback (most recent call last):
File "train.py", line 60, in
train_dataset = dataset.lmdbDataset(root=opt.trainRoot)
File "/home/haha/Documents/Workspaces/Workspace-PyCharm/crnn-pytorch/dataset.py", line 32, in init
nSamples = int(txn.get('num-samples'.encode()))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
不清楚是什么原因导致的。

**Comment by zcswdt** [comment]
> 或者把你的数据集和公开的数据集混合起来重新训练，并且生成数据和公开数据比例不能差太大。

我想训练的模型是用户上传的繁体字模型，然后公开数据集上好像并没有这些数据集啊，你知道有这样的数据集吗？

**Comment by zcswdt** [comment]
> 到您已经调试出来

我没有遇见你这样的问题啊，你看看哪个大佬知道

**Comment by allenxcp** [comment]
> > 推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec
> 
> 谢谢回复，我也用了这个，但是有问题啊，我自己合成300万的280*32定长十字的图片，但是训练出来的模型，在测试集里面表现效果好，测试图片高度宽度大小不和生成的图片一致或者是出入太大的时候就识别错误，请问这样有什么好的解决方法？

**Comment by yyyash8** [comment]
> > Fortunately, I debugged successfully, and I can already train and test normally.
> 
> Hello, did you encounter this problem during training:
> Traceback (most recent call last):
> File "train.py", line 60, in
> train_dataset = dataset.lmdbDataset (root = opt.trainRoot)
> File "/ home / haha ​​/ Documents / Workspaces / Workspace-PyCharm / crnn-pytorch / dataset.py ", line 32, in init
> nSamples = int (txn.get ('num-samples'.encode ()))
> TypeError: int () The argument must be a string, a bytes-like object or a number, not 'NoneType' is
> not clear what caused it.

Did you solve this issue?

**Comment by zcswdt** [comment]
> > > 推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec
> > 
> > 
> > 谢谢回复，我也用了这个，但是有问题啊，我自己合成300万的280*32定长十字的图片，但是训练出来的模型，在测试集里面表现效果好，测试图片高度宽度大小不和生成的图片一致或者是出入太大的时候就识别错误，请问这样有什么好的解决方法？
> 
> 这个问题说明是模型泛化性不好。测试的时候，首先高度一定要32；其次你训练数据集是自己生成的，应该是复杂度不够，太单调了，所以你在测试集上有效果，在其他非测试集图片上效果就不行了。给你的建议是用公开数据集，或者把你的数据集和公开的数据集混合起来重新训练，并且生成数据和公开数据比例不能差太大。

老哥，有个问题请教你，就是我要是训练不定长的图片，这个还需要修改什么吗？

**Comment by HandsomeHans** [comment]
> > @zcswdt 训练出来啦，你请说。
> 
> > 还好吧，我调试成功，已经能正常训练和测试了。
> 
> 您好，看到您已经调试出来了，所以很突兀的就过来问你，请问您知道我这个是怎么回事吗
> ![image](https://user-images.githubusercontent.com/47933430/82774668-11caf800-9e78-11ea-96cd-509cff015268.png)

你这个问题是warpctc没安装明白，我建议你使用torch自带的ctc_loss。可以参考中文识别那个项目，我记得他里面是用的torch自带的。

**Comment by HandsomeHans** [comment]
> > 还好吧，我调试成功，已经能正常训练和测试了。
> 
> 你好，请问在训练的时候有碰到过这个问题吗：
> Traceback (most recent call last):
> File "train.py", line 60, in
> train_dataset = dataset.lmdbDataset(root=opt.trainRoot)
> File "/home/haha/Documents/Workspaces/Workspace-PyCharm/crnn-pytorch/dataset.py", line 32, in init
> nSamples = int(txn.get('num-samples'.encode()))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> 不清楚是什么原因导致的。

读取txn文件的时候，加上encoding='utf-8'

**Comment by HandsomeHans** [comment]
> > 或者把你的数据集和公开的数据集混合起来重新训练，并且生成数据和公开数据比例不能差太大。
> 
> 我想训练的模型是用户上传的繁体字模型，然后公开数据集上好像并没有这些数据集啊，你知道有这样的数据集吗？

那就自己生成，我给你推荐一个自己合成文字识别数据集的项目：[TextRecognitionDataGenerator](https://github.com/Belval/TextRecognitionDataGenerator)

**Comment by HandsomeHans** [comment]
> > > > 推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec
> > > 
> > > 
> > > 谢谢回复，我也用了这个，但是有问题啊，我自己合成300万的280*32定长十字的图片，但是训练出来的模型，在测试集里面表现效果好，测试图片高度宽度大小不和生成的图片一致或者是出入太大的时候就识别错误，请问这样有什么好的解决方法？
> > 
> > 
> > 这个问题说明是模型泛化性不好。测试的时候，首先高度一定要32；其次你训练数据集是自己生成的，应该是复杂度不够，太单调了，所以你在测试集上有效果，在其他非测试集图片上效果就不行了。给你的建议是用公开数据集，或者把你的数据集和公开的数据集混合起来重新训练，并且生成数据和公开数据比例不能差太大。
> 
> 老哥，有个问题请教你，就是我要是训练不定长的图片，这个还需要修改什么吗？

一般会把图片resize到固定长度好batch训练，如果你图片长度不定，可以先等比例缩小图片到高度32，这时候长度为w，然后将长度统一padding到w_max，这样才能batch训练，最后在计算ctc loss的时候给出长度w。可以参考下面代码：

1. criterion = torch.nn.CTCLoss() # 实例化ctc loss对象

2. cost = criterion(preds, text, preds_size, length) # preds是网络输出，text是gt label， preds_size这里面是输入中每一个图片的w， length是batch size

注意原本代码中preds_size是计算的preds长度，如果原始数据不定长的话，需要你按顺序传入每一张图片的w。具体为什么可以了解一下ctc机制。

**Comment by xiao12mm** [comment]
> 推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec

果然是好代码，快让这个第二名的代码坑死了！！！！！！！！！！！！！！！！！！！

**Comment by sssimpleboy** [comment]
> 还好吧，我调试成功，已经能正常训练和测试了。
请问你有没有出现过  ctc 的错误
RuntimeError: CUDA error: an illegal memory access was encountered
试了各种方法都不能解决呀~

**Comment by allenxcp** [comment]
@sssimpleboy   推荐使用 https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec
