### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by xiaomeng654321** [meijieru/crnn.pytorch#225]
I can't find the reason  why this error occurs? Help me resolve this.
buf.write(imgbuf)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by GarhwalRifles** [comment]
how did you resolve this

**Comment by xiaomeng654321** [comment]
the real reason is that the https://github.com/meijieru/crnn.pytorch/issues/147,  i  can't deal with the #147 problem using python 3.6
