### ISSUE TITLE
Why only use lowercase letters?

### ISSUE THREAD

**Issue by xinghedyc** [meijieru/crnn.pytorch#24]
I mean ICDAR2013 evaluation includes uppercase letters right ?

**Comment by ahmedmazari-dhatim** [comment]
@xinghedyc , l noticed that also. The model take into consideration only lowercase. It transforms the uppercase letters to lowercase .
l'm wondering if there is any way to push the model to take into consideration lowercase and uppercase  at the same time !

**Comment by meijieru** [comment]
You could change this setting by modify the dictionary.
