### ISSUE TITLE
 raise StopIteration error in crrn_main.py DUE to max_iter 

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [meijieru/crnn.pytorch#25]
Hello,

in crnn_main.py  line  `125`   the function `def val(net, dataset, criterion, max_iter=100):`  takes a a parameter `max_iter` which by default is set to` 100` . However, it doesn't work for any dataset ( but in the article the max iteration is between 200k and 500k). For huge dataset `max_iter=100` works but for small one : 
you should reduce the value manually.
For instance l tried two small dataset the first worked with` max_iter=49` and another one with` max_iter=22` and another one with `max_iter=5`
otherwise l get the following error
```
[0/35][1/13] Loss: 65.981506
Start val
Traceback (most recent call last):
  File "crnn_main.py", line 216, in <module>
    val(crnn, test_dataset, criterion)
  File "crnn_main.py", line 144, in val
    data = val_iter.next()
  File "/home/ahmed/anaconda3/envs/cv/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 202, in __next__
    raise StopIteration
StopIteration
```

l reached to set manually `max_iter` as follow : 
putting  `print(i)` in line `141`
```
   for i in range(max_iter):
            print(i)
           data = val_iter.next()
  
```
to see after which iteration it returns  raise `StopIteration error`

How to solve that ?

Thank you

**Comment by meijieru** [comment]
You should set the option `niter` instead of this one.

**Comment by ahmedmazari-dhatim** [comment]
@meijieru , 
When l add `--niter="30" `  and let `max_iter=100` as it is set by default l get the same error related to  max_iter
`python2 crnn_main.py --trainroot="model/train/" --valroot="model/valid/" --imgH=32 --cuda --niter="30"  --adadelta  --experiment="/model/output/"`

**Comment by meijieru** [comment]
I have fixed it in [this commit](https://github.com/meijieru/crnn.pytorch/commit/42346e159a8843ee1cf17fb6b23bf9846b537d8c)

**Comment by ahmedmazari-dhatim** [comment]
@meijieru , thank you but it returns the same error

**Comment by meijieru** [comment]
Sorry, I have made a type error, it should work now.

**Comment by ahmedmazari-dhatim** [comment]
@meijieru , thanks it works
