### ISSUE TITLE
How can l get the probability of the sequence outputted by CRNN ?

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [meijieru/crnn.pytorch#27]
Hello,

l'm wondering whether the CRNN is able to output also the probability of each sequence 

from example :  

--h-e--ll-oo- => 'hello'   with a probability= 0.89 
for instance 
how can l get that ?

**Comment by meijieru** [comment]
I recommend you to carefully read the origin paper and `CTC` paper.
The output of CTC is the log-likelihood, so you could retrieve the prob. by simply $ p(s) = exp(-L) $ (just for a reference).

**Comment by ahmedmazari-dhatim** [comment]
@meijieru , thank you

**Comment by ahmedmazari-dhatim** [comment]
@meijieru,
Thanks à lot, l read the article, l understand better now. However in the code `CTCLoss` can't find these probabilites .

In  `__init__.py`  the `CTC` class is defined as follow : 

However l don't find where to print the output probabilities here.
```
class _CTC(Function):
    def forward(self, acts, labels, act_lens, label_lens):
        is_cuda = True if acts.is_cuda else False
        acts = acts.contiguous()
        loss_func = warp_ctc.gpu_ctc if is_cuda else warp_ctc.cpu_ctc
        grads = torch.zeros(acts.size()).type_as(acts)
        minibatch_size = acts.size(1)
        costs = torch.zeros(minibatch_size)
        loss_func(acts,
                  grads,
                  labels,
                  label_lens,
                  act_lens,
                  minibatch_size,
                  costs)
        self.grads = grads
        self.costs = torch.FloatTensor([costs.sum()])
        return self.costs

    def backward(self, grad_output):
        return self.grads, None, None, None


class CTCLoss(Module):
    def __init__(self):
        super(CTCLoss, self).__init__()

    def forward(self, acts, labels, act_lens, label_lens):
        """
        acts: Tensor of (seqLength x batch x outputDim) containing output from network
        labels: 1 dimensional Tensor containing all the targets of the batch in one sequence
        act_lens: Tensor of size (batch) containing size of each output sequence from the network
        act_lens: Tensor of (batch) containing label length of each example
        """
        _assert_no_grad(labels)
        _assert_no_grad(act_lens)
        _assert_no_grad(label_lens)
        return _CTC()(acts, labels, act_lens, label_lens)
```

**Comment by Amschel** [comment]
Hi @meijieru, @ahmedmazari-dhatim.

I'm looking aswell to find a way to get the score/probabilities but I can't find the code sequence where it is defined.

Any solutions?

Thank you for your time and patience!
Amschel.

**Comment by ahmedmazari-dhatim** [comment]
Hi @Amschel,
Still getting stuck at it. l didn't find a way to get these probabilities . l let you know if l find something. Please do the same.

Thank you

**Comment by ahmedmazari-dhatim** [comment]
Hello @Amschel,

Anything new ?

Thank you

**Comment by random123user** [comment]
@ahmedmazari-dhatim 

have a look at #40 , it can be helpful.
