### ISSUE TITLE
sixlmdp_train_data_ordered module is missing

### ISSUE THREAD

**Issue by daobilige-su** [meijieru/crnn.pytorch#3]
Hi Jieru,

Thanks for your previous answer. I managed to create my own dataset. However, when I ran the "crnn_main.py" file with args specifying the training and testing dataset (with everything else the same as default value), it gave me errors as follows:

```
Traceback (most recent call last):
  File "/home/su/work_space/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/su/work_space/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/su/work_space/MOCR/crnn.pytorch/crnn_main.py", line 13, in <module>
    import dataset
  File "/home/su/work_space/MOCR/crnn.pytorch/dataset.py", line 10, in <module>
    import sixlmdp_train_data_ordered
ImportError: No module named sixlmdp_train_data_ordered
```
Does it mean the python module "sixlmdp_train_data_ordered" is somehow missing? Is it a custom module defined by yourself? I made a bit of search, but I can't find it anywhere online. Many thanks.

Cheers,

Su

**Comment by meijieru** [comment]
why do you import a module name `sixlmdp_train_data_ordered`? you should only specify the `trainroot` and `valroot` to it.

**Comment by daobilige-su** [comment]
Thanks for the prompt reply.

The `sixlmdp_train_data_ordered` module is called by "dataset.py" (line 10), which is called by "crnn_main.py" file (line 13).

**Comment by daobilige-su** [comment]
AH...
Sorry, my file is corrupted. It is import six in your original file, but somehow it is changed in my local copy. Sorry about it.

Have a nice weekend.

Su
