### ISSUE TITLE
run python demo.py , failed reporting error ：dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by emily2he** [meijieru/crnn.pytorch#31]
When I run "python demo.py", but failed, met these error:

loading pretrained model from ./data/crnn.pth
Traceback (most recent call last):
  File "demo.py", line 30, in <module>
    preds = preds.squeeze(2)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 704, in squeeze
    return Squeeze.apply(self, dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/tensor.py", line 341, in forward
    result = input.squeeze(dim)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

could you help me how to solve this problem?

**Comment by meijieru** [comment]
I could not reproduce this problem. 

Could you please check the shape of this variable?

**Comment by emily2he** [comment]
I according to the README.md, do nothing other. I got this error:
 RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

I don't know what this error mean, so I cann't debug this problem
Could you tell me what expect in range [ -2, 1] and what got 2 according this error?
thanks

**Comment by emily2he** [comment]
I according to the README.md, do nothing other. I got this error:
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

I don't know what this error mean, so I cann't debug this problem
Could you tell me what expect in range [ -2, 1] and what got 2 according this error?
thanks

**Comment by meijieru** [comment]
Could you call `print(preds.size())` before the problem happens?

I don't know what should be that too.

**Comment by emily2he** [comment]
after add print, report : torch.Size([26, 1, 37])

**Comment by meijieru** [comment]
It should be `[1, 26, 1, 37]`

**Comment by hellbago** [comment]
I have the same problem. Have you solved this issue? @emily2he

**Comment by emily2he** [comment]
@meijieru 
"preds" come out of "model(image)", though "model" come out of:
model_path = './data/crnn.pth'
model = crnn.CRNN(32, 1, 37, 256, 1).cuda()
model.load_state_dict(torch.load(model_path))

so I think maybe the model is not right, I down load from "Baidu Netdisk"
@hellbago  sorry, I haven't solved

**Comment by hellbago** [comment]
@emily2he  try to comment out this line of code : 
`preds = preds.squeeze(2)`
For me it works

**Comment by meijieru** [comment]
It is a problem of pytorch version, and it has been fixed.

**Comment by rdp** [comment]
which version of pytorch fixes this anybody know?
