### ISSUE TITLE
Error while converting crnn_demo_model.t7 into a .pth model

### ISSUE THREAD

**Issue by rayush7** [meijieru/crnn.pytorch#32]
@meijieru  
I am trying to convert the crnn_demo_model.t7 into an equivalent .pth model using the script convert_t7.py but I am getting the following error.

  File "tool/convert_t7.py", line 167, in <module>
    torch_to_pytorch(py_model, args.model_file, args.output)
  File "tool/convert_t7.py", line 130, in torch_to_pytorch
    if layer_map[t7_name] != py_name:
  KeyError: 'b'

Please help me to rectify this issue.

**Comment by meijieru** [comment]
How does the `crnn_demo_model.t7` generated?

**Comment by Titannet** [comment]
https://www.dropbox.com/s/tx6cnzkpg99iryi/crnn_demo_model.t7?dl=0

**Comment by rayush7** [comment]
I just downloaded the crnn_demo_model. t7 as mentioned [here](https://github.com/bgshih/crnn)

**Comment by Titannet** [comment]
Yes, that file does not convert. KeyError: 'b'

**Comment by rayush7** [comment]
Yeah I too want to convert my own model .t7 model in .pth format. I was trying to convert my own model as well the standard model provided by CRNN author but the aforementioned error is occurring. I hope @meijieru can help.

**Comment by meijieru** [comment]
You should save the t7 model by `convert_t7.lua`.

**Comment by Titannet** [comment]
Thx! Conversion was correct, but the result is: 333333333333333333333333t8 => 3t8

**Comment by rayush7** [comment]
Yes its working. There is slight difference in sequence predicted by the .t7 model and the sequence predicted by .pth model for the same image. But its working without any bug. Thanks @meijieru @Titannet

**Comment by huoo2015** [comment]
when i use convert_t7.lua, the problem is:
./convert_t7.lua:54: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        ./convert_t7.lua:54: in function 'modelToList'
        ./convert_t7.lua:86: in main chunk
        [C]: in function 'dofile'
        ...hdtk/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
why ?

**Comment by stalagmite7** [comment]
How do you actually use the convert_t7.lua to convert the original crnn_demo_model.t7? I don't see any arguments that the script takes..

**Comment by stalagmite7** [comment]
@huoo2015 , have you figured out the error? I am facing the same issue

**Comment by rayush7** [comment]
@stalagmite7 You need to load the .t7 model and then call the savemodel function on it to create another .t7 model, which can be converted into a corresponding .pth mode.

Check this out (convert_t7.lua)

require('cutorch')
require('nn')
require('cunn')
require('cudnn')
require('table')
require('torch')
require('os')
require('optim')
require('paths')
require('nngraph')

require('libcrnn')
require('utilities')
require('inference')
require('CtcCriterion')
require('DatasetLmdb')
require('LstmLayer')
require('BiRnnJoin')
require('SharedParallelTable')



function clone(t)
    -- deep-copy a table
    if type(t) ~= "table" then return t end
    local meta = getmetatable(t)
    local target = {}
    for k, v in pairs(t) do
        if type(v) == "table" then
            target[k] = clone(v)
        else
            target[k] = v
        end
    end
    setmetatable(target, meta)
    return target
end


function tableMerge(lhs, rhs)
    output = clone(lhs)
    for _, v in pairs(rhs) do
        table.insert(output, v)
    end
    return output
end


function isInTable(val, val_list)
    for _, item in pairs(val_list) do
        if val == item then
            return true
        end
    end
    return false
end


function modelToList(model)
    local ignoreList = {
        'nn.Copy',
        'nn.AddConstant',
        'nn.MulConstant',
        'nn.View',
        'nn.Transpose',
        'nn.SplitTable',
        'nn.SharedParallelTable',
        'nn.JoinTable',
    }
    local state = {}
    local param
    for i, layer in pairs(model.modules) do
        local typeName = torch.type(layer)
        if not isInTable(typeName, ignoreList) then
            if typeName == 'nn.Sequential' or typeName == 'nn.ConcatTable' then
                param = modelToList(layer)
            elseif typeName == 'cudnn.SpatialConvolution' or typeName == 'nn.SpatialConvolution' then
                param = layer:parameters()
            elseif typeName == 'cudnn.SpatialBatchNormalization' or typeName == 'nn.SpatialBatchNormalization' then
                param = layer:parameters()
                bn_vars = {layer.running_mean, layer.running_var}
                param = tableMerge(param, bn_vars)
            elseif typeName == 'nn.LstmLayer' then
                param =  layer:parameters()
            elseif typeName == 'nn.BiRnnJoin' then
                param =  layer:parameters()
            elseif typeName == 'cudnn.SpatialMaxPooling' or typeName == 'nn.SpatialMaxPooling' then
                param = {}
            elseif typeName == 'cudnn.ReLU' or typeName == 'nn.ReLU' then
                param = {}
            else
                print(string.format('Unknown class %s', typeName))
                os.exit(0)
            end
            table.insert(state, {typeName, param})
        else
            print(string.format('pass %s', typeName))
        end
    end
    return state
end


function saveModel(model, output_path)
    local state =  modelToList(model)
    torch.save(output_path, state)
end

----------------Editing the Script---------------------------

print('Loading model...')
local modelDir = '/home/ubuntu/crnn/input_model/'
paths.dofile(paths.concat(modelDir, 'config.lua'))
local modelLoadPath = paths.concat(modelDir, 'crnn_demo_model.t7')
gConfig = getConfig()
gConfig.modelDir = modelDir
gConfig.maxT = 0
local model, criterion = createModel(gConfig)
local snapshot = torch.load(modelLoadPath)
loadModelState(model, snapshot)


-- saving the model
saveModel(model,'/home/ubuntu/output_model/crnn_demo_model_new.t7')

**Comment by angel1288** [comment]
@huoo2015 Have you solved this problem?
