### ISSUE TITLE
how to run with cpu

### ISSUE THREAD

**Issue by exgile** [meijieru/crnn.pytorch#35]
i want some data about running with CPU, how can i turn off CUDA ?

**Comment by meijieru** [comment]
just unset the flag `--cuda`.

**Comment by lg12170226** [comment]
you using --cuda ok？ @exgile

**Comment by hellbago** [comment]
How to disable/enable GPU for demo.py? @meijieru

**Comment by lg12170226** [comment]
@hellbago [https://github.com/SeanNaren/warp-ctc/tree/pytorch_bindings/pytorch_binding](url) Reference Readme.

**Comment by meijieru** [comment]
By default, it runs with cuda enabled.
If you really want to run `demo.py` using cpu, just delete `.cuda()` in the file.

**Comment by wulivicte** [comment]
@meijieru i have  delete .cuda() in the file,  error occurred：
![1](https://user-images.githubusercontent.com/22539027/27680934-0c900bd6-5cf0-11e7-8968-89ba8e4117ab.jpg)

**Comment by meijieru** [comment]
@wulivicte Could you please try the updated code?
