### ISSUE TITLE
using gpu error:"'module' object has no attribute 'gpu_ctc'"

### ISSUE THREAD

**Issue by lg12170226** [meijieru/crnn.pytorch#36]
run crnn_main.py using --cuda,and then error.
Error content：loss_func = warp_ctc.gpu_ctc if is_cuda else warp_ctc.cpu_ctc
                        AttributeError:'module' object has no attribute 'gpu_ctc'.
How to deal with?

**Comment by meijieru** [comment]
Please ensure the `warp_ctc` is built with gpu support.

**Comment by lg12170226** [comment]
@meijieru thank u for your help . i have solved the problem

**Comment by rohun-tripathi** [comment]
@lg12170226 How did you solve the problem? I get the exact same issue

**Comment by lg12170226** [comment]
@rohun-tripathi  sorry for long time. Before installing pytorch_binding, make sure to set CUDA_HOME, compile and install will not complain, but when calling gpu wrap_ctc there will be no gpu attribute error
