### ISSUE TITLE
Issue with LMDB file while learning

### ISSUE THREAD

**Issue by kergann** [meijieru/crnn.pytorch#38]
Hello,

I've created a LMDB file with Caffe but i have some issues while reading it with six.BytesIO() so i can't get the names of my images. It tells me that my images are corrupted (but the name in the lmdb is right).
Is there any other methods to create a LMDB file (without Caffe maybe) or other suggestions ? 

I'm working on Ubuntu 16.04 with python3.4

Thank you in advance.
Best regards

**Comment by meijieru** [comment]
It could be better to ask it on stackoverflow for fast response

**Comment by kergann** [comment]
Thank you for the response but i am trying to run crnn_main.py with my datas (lmdb files) but when it arrives to buf = six.BytesIO() in dataset.py it crashed saying he can't read my files (corrupted image).

My question would be, do you run crnn_main.py (to train) with lmdb files (folder that contains lmdb files) and if so how did you create those lmdb files ?  If you did it with Caffe like me, I may have done something wrong.

**Comment by meijieru** [comment]
1. yes
2. with python's `lmdb` lib

**Comment by wulivicte** [comment]
@kergann hi, did you solve the problem? I have solved this problem and modified the script that generated lmdb, you can refer to my changes。

**Comment by kergann** [comment]
Hello,

I've actually changed your code to work with h5py files (which was more suited for my problem). Everything seems to work now, happy to see the lmdb problem fixed though.

Best

**Comment by hellbago** [comment]
Do you use python2 or python3? @meijieru 
Actually i think this problem is related to python3 encoding

**Comment by hellbago** [comment]
I'm using python 3.5.2 and when I launch 
```
python crnn_main.py --trainroot dataset/lmdb_output_rotated_maxplate1_minchar5/ --valroot dataset/lmdb_output_norotated_maxplate1_minchar5/ --cuda --keep_ra
tio --batchSize 5 --niter 1
```
 I get the following error:
  File "/home/ubuntu-andrea/CRNN2/crnn.pytorch/dataset.py", line 32, in __init__
    nSamples = int(txn.get('num-samples'))
TypeError: Won't implicitly convert Unicode to bytes; use .encode()

I don't know if the problem is related to python 3. Any advice about this issue?

**Comment by adam-slucki** [comment]
Adding ".encode()" to every string used with txt should solve the issue with lmdb.
So:
`nSamples = int(txn.get('num-samples'))`
Should be:
`nSamples = int(txn.get('num-samples'.encode()))`

**Comment by BobbleHeadAlien** [comment]
@adam-slucki , thank you for pointing out the encode() error. But i am getting a different error now. I was hoping you could help me out.

I made the required changes to the dataset file. but now im getting the below error:

`Traceback (most recent call last):
  File "crnn_main.py", line 59, in <module>
    train_dataset = dataset.lmdbDataset(root=opt.trainroot)
  File "/new/Kaushik/crnn.pytorch_1/dataset.py", line 32, in __init__
    nSamples = int(txn.get('num-samples'.encode()))
ValueError: invalid literal for int() with base 10: b''
`

Can anyone please tell me why im getting this? I know that we get this message when the int contains either a non-int character or is empty. 
I am using python 3.6 and pytorch 0.4.

I am using the mjsynth dataset. I prepared the dataset according to the original instructions. I have the training data stored in a folder which has two files namely "data.mdb" and "lock.mdb". this is the folder i mentioned when passing the training command input as well. 

Please help me out here. thankyou.

**Comment by thatindiandude** [comment]
nSamples = int(txn.get('num-samples'.encode()).decode())
