### ISSUE TITLE
cnn height equals 1 assertion error

### ISSUE THREAD

**Issue by daobilige-su** [meijieru/crnn.pytorch#4]
Hi Jieru,

Sorry for the previous question. 
I cloned the code again and this time I'm getting cnn height equals 1 assertion error in `crnn.py`.

```
    def forward(self, input):
        # conv features
        conv = utils.data_parallel(self.cnn, input, self.ngpu)
        b, c, h, w = conv.size()
        assert h == 1, "the height of conv must be 1"
```
In the code, the `input` is of dimension 64x1x64x128 (`[torch.cuda.FloatTensor of size 64x1x64x128 (GPU 0)]`), and the `conv` size has become 64x512x3x33 (b=64, c=512, h=3, w=33). Could you please give me any hint on how to resolve it? My training data is sub-sample from synth90k, so if I am correct, the image should be gray scale. Many thanks.

Cheers,

Su

**Comment by meijieru** [comment]
1. The stride is special designed for height 32, otherwise it will not satisfy our assumption.
2. It should be convert into gray scale.

**Comment by ahmedmazari-dhatim** [comment]
Hi  @daobilige-su  how did you solve the problem ? thank you
