### ISSUE TITLE
Any ideas on variable length input images rather than resizing it ?

### ISSUE THREAD

**Issue by rremani** [meijieru/crnn.pytorch#54]
Tried resizing and using on crnn but wasn't successful, any suggested readings or modification would be appreciated!

**Comment by meijieru** [comment]
Just resize the height to 32 and keep the ratio of the image

**Comment by rremani** [comment]
So you mean to say it has nothing to do with the width, I did the same as you mentioned  while using torch but it didnt work, there in dataloader things were hard coded(resize) before image is input to the model.

**Comment by meijieru** [comment]
There is option to keep the ratio of data.

**Comment by rremani** [comment]
Thanks, I just checked it now.
