### ISSUE TITLE
 AWS AMAZON ValueError(‘sampler is mutually exclusive with shuffle’) 

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [meijieru/crnn.pytorch#55]

**Comment by lewisgit** [comment]
Could you please share your solution with us?

**Comment by ahmedmazari-dhatim** [comment]
parser.add_argument('--random_sample', action='store_true',default=True, help='whether to sample the dataset with random sampler')

**Comment by gachiemchiep** [comment]
Thank you @ahmedmazari-dhatim 

I got it now. In the DataLoader, the "shuffle" is True so sampler should be None object.

    train_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=opt.batchSize,
    shuffle=True, sampler=sampler,
    num_workers=int(opt.workers),
    collate_fn=dataset.alignCollate(imgH=opt.imgH, imgW=opt.imgW, keep_ratio=opt.keep_ratio))

In the code

     parser.add_argument('--random_sample', action='store_true', help='whether to sample the dataset with random sampler')

We should change into

    parser.add_argument('--random_sample', action='store_true', default=True, help='whether to sample the dataset with random sampler')

@lewisgit 
Hope that help

**Comment by jamesbondzhou** [comment]
i met the same problem with you first,so i changed:
 parser.add_argument('--random_sample', action='store_true',default=True_, help='whether to sample the dataset with random sampler')
but i got another error:
    collate_fn=dataset.alignCollate(imgH=opt.imgH, imgW=opt.imgW, keep_ratio=opt.keep_ratio))
  File "D:\program\workspace\python 3.5\lib\site-packages\torch\utils\data\dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "D:\program\workspace\python 3.5\lib\site-packages\torch\utils\data\sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0
@ahmedmazari-dhatim
