### ISSUE TITLE
How CTC deals with successive doubled characters ? 

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [meijieru/crnn.pytorch#56]
Hello,

`F(ab)= ab `and `F(aa)=a and not (aa)` it's like you say for` F(ab)= ab` are adjacent characters where `a b` are two characters of different columns of the image but when it comes to `F(aa) = a` it means that the CTC sees the same column ( char overlapping ) ?

How do you explain the fact that` F(ab)= ab and F(aa) != aa and F(aa) = a  and F(a-a)=aa` ?

It's like we say that two successive symbols should either be different or be separated by a blank. But we can have two successive symbols are the same such as` tt `in `letter `
Thank you

**Comment by meijieru** [comment]
Yeah, for successive doubled characters, it requires the network to ensure the separate `blank` exist. Network could recognize them.

**Comment by ahmedmazari-dhatim** [comment]
Hi @meijieru ,

Thank you. Why it require separate blank exist between two successive doubled symbols and not for different symbols ? How could we explain that ?

Thank you

**Comment by meijieru** [comment]
There could be.
`blank` character is for separate doubled symbols, for different symbols, there could be or not.

**Comment by ahmedmazari-dhatim** [comment]
@meijieru , why we need to separate doubled symbols ?

**Comment by gdjmck** [comment]
When dealing with car plate recognition, I find it pretty hard for two same character coming in a row. It usually predicts 'aaaaaaaaaaa' take 'aa' for example, failing to predict 'aaa--aaaa'. Would it be a matter of the "receptive field" of the convolution layer?
Or are there any technique that solves this problem? I'm a little bit new to this field and haven't read much papers.
