### ISSUE TITLE
Warp-CTC vs CTC ?

### ISSUE THREAD

**Issue by ibrahimsoliman97** [meijieru/crnn.pytorch#57]
Hello, 

May I know if you notice any differences in the training performance after implementing warp-CTC rather than original ctc from the author (bgshih) ? because as stated on the warp CTC announcement "warp ctc is 10 to 400 times faster than any other ctc implementations"

Thanks for your efforts..

**Comment by meijieru** [comment]
They should work the same because they implementing the same algorithm.
I did not observed any difference until now.

**Comment by ibrahimsoliman97** [comment]
Great !
Thanks for your reply..
