### ISSUE TITLE
key error when running demo with fine-tuned model?

### ISSUE THREAD

**Issue by lewisgit** [meijieru/crnn.pytorch#59]
loading pretrained model from ./data/netCRNN_1_4.pth
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    model.load_state_dict(torch.load(model_path))
  File "C:\Users\sudol\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.cnn.conv0.weight" in state_dict'

I encounter this error when  running demo with fine-tuned model.
could you please give a hint why this happens?
i didn't change the network, just load crnn.pth and fine-tune with new dataset.

**Comment by lewisgit** [comment]
I searched for the solution online, seems that it might related to nn.DataParallel, but I still don't know the answer, would you please help me about this?

**Comment by lewisgit** [comment]
I solved my problem. I have only one GPU, therefore no need for data parallel training.
i use crnn.cuda() only
compare the validation result between crnn.cuda() and data parallel training
crnn.cuda() 's training converges better on my training set, which is quite curious.

one more question, when I store state_dict when running data parallel training, how can I load the model correctly?

**Comment by meijieru** [comment]
Just restore as normal

**Comment by rremani** [comment]
Hi,
I got the same problem, my alphabets are ABCDEFGHIJKLMNOPQRSTUVWXYZabdefghnqrt, have 37 classes.
model = crnn.CRNN(32, 1,38, 256)
if torch.cuda.is_available():
    model = model.cuda()
print('loading pretrained model from %s' % model_path)
model.load_state_dict(torch.load(model_path))
while loading got this error:
loading pretrained model from data/models/netCRNN_24_1000.pth
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model.load_state_dict(torch.load(model_path))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 356, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.cnn.conv0.weight" in state_dict'

**Comment by liuhu-bigeye** [comment]
@rremani If you run `crnn = torch.nn.DataParallel(crnn, device_ids=range(opt.ngpu))` in crnn_main.py before saving in training epochs, just do the same before `model.load_state_dict(torch.load(model_path))` in your test.py

**Comment by rremani** [comment]
@liuhu-bigeye Thanks a lot!

**Comment by CXY573** [comment]
＠liuhu-bigeye 　i have change my code 
model = torch.nn.DataParallel(model,device_ids=range(1))
but another error occur,
KeyError: 'unexpected key "cnn.0.weight" in state_dict'
do you have any ideal with it

**Comment by Aurora11111** [comment]
@liuhu-bigeye thanks!
