### ISSUE TITLE
unexpected key "module.cnn.conv0.weight" in state_dict

### ISSUE THREAD

**Issue by Bilgee** [meijieru/crnn.pytorch#60]
I trained models using own dataset. But when I load the saved models, it keeps saying that "unexpected key "module.cnn.conv0.weight" in state_dict". What do I have to do? I am just started learning pytorch

**Comment by Bilgee** [comment]
I have solved the issue. I changed the source code a little bit. 
    # model = model.cuda()
    model = torch.nn.DataParallel(model).cuda()

**Comment by meijieru** [comment]
Feel free to create a PR.

**Comment by cwfxcz** [comment]
Another solution to this problem: simply revise the keys of the loading state_dict:
```python
if opt.crnn != '':
    print('loading pretrained model from %s' % opt.model_path)
    state_dict = torch.load(opt.model_path)
    state_dict_rename = OrderedDict()
    for k, v in state_dict.items():
        name = k[7:] # remove `module.`
        state_dict_rename[name] = v
    crnn.load_state_dict(state_dict_rename)
