### ISSUE TITLE
AssertionError: texts with length: 1664 does not match declared length: 6656

### ISSUE THREAD

**Issue by haikuoyao** [meijieru/crnn.pytorch#62]
Hi,

I got this error when I trained with multi-gpu.
```
assert t.numel() == length.sum(), "texts with length: {} does not match declared length: {}".format(t.numel(), length.sum())
AssertionError: texts with length: 1664 does not match declared length: 6656
```

I saw [issue 41](https://github.com/meijieru/crnn.pytorch/issues/41). It's same as it. 
But it seems it's already updated in the current code. 

Is there any way to fix this?

Thanks.

**Comment by meijieru** [comment]
Could you please give me a minimal example to reproduce this problem?

**Comment by haikuoyao** [comment]
Hi @meijieru This issue has been fixed. I'll close this issue.
Thanks a lot.

**Comment by ku21fan** [comment]
Hi, same error msg occurred to me.
I found hints to solve from [here](http://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html)

> In general, pytorch’s nn.parallel primitives can be used independently. We have implemented simple MPI-like primitives:
> 
> replicate: replicate a Module on multiple devices
> scatter: distribute the input in the first-dimension
> gather: gather and concatenate the input in the first-dimension
> parallel_apply: apply a set of already-distributed inputs to a set of already-distributed models.

I solved this issue with 'batch_first=True' at LSTM. (with default setting, the first-dimension of LSTM input/output is Timestep)
and then changed all the things corresponding to batch_first.
including 
```
class BidirectionalLSTM(nn.Module):

    def __init__(self, nIn, nHidden, nOut):
        super(BidirectionalLSTM, self).__init__()

        self.rnn = nn.LSTM(nIn, nHidden, bidirectional=True, batch_first = True)
        self.embedding = nn.Linear(nHidden * 2, nOut)

    def forward(self, input):
        self.rnn.flatten_parameters()
        recurrent, _ = self.rnn(input)

        b, T, h = recurrent.size()
        t_rec = recurrent.contiguous().view(b * T, h)

        output = self.embedding(t_rec)  # [b * T, nOut]
        output = output.view(b, T, -1)

        return output
```

```
    def forward(self, input):
        # conv features
        conv = self.cnn(input)
        b, c, h, w = conv.size()
        assert h == 1, "the height of conv must be 1"
        conv = conv.squeeze(2)
        #conv = conv.permute(2, 0, 1)  # [w, b, c]
        conv = conv.permute(0, 2, 1)  # [b, w, c]

        # rnn features
        output = self.rnn(conv)

        return output
```

and in function `trainBatch`, `val`
```
    preds = crnn(image)
    preds_size = Variable(torch.IntTensor([preds.size(1)] * batch_size))
    preds = preds.permute(1, 0, 2) # to use CTCloss format ? 
    cost = criterion(preds, text, preds_size, length) / batch_size
```

hope it helps, thanks.

**Comment by meijieru** [comment]
Thanks @ku21fan , and #63 maybe solve

**Comment by rabbithui** [comment]
@ku21fan i can train with multi-gpu with your method, but i found the training time is much more than  with one gpu. Did you meet this problem?

**Comment by vinayakkailas** [comment]
@ku21fan when i used your code i get this error

 RuntimeError: torch/csrc/autograd/variable.cpp:115: get_grad_fn: Assertion `output_nr == 0` failed.

**Comment by ku21fan** [comment]
Sorry for rate reply.
@rabbithui I didn't meet that problem. When I do multi-gpu training with 2 or 4 gpus, training time is faster, but accuracy was slightly down at the same epoch with 1 gpu training.

@vinayakkailas @maichm I didn't get that error.. 
[this link](https://github.com/pytorch/pytorch/issues/7092#issuecomment-385357970 )  might helps . hope it works !

**Comment by mengzhibin** [comment]
> Hi @meijieru This issue has been fixed. I'll close this issue.
> Thanks a lot.

how do you solve this problem?  looking for your reply @haikuoyao
