### ISSUE TITLE
Training dataset for the Dropbox model

### ISSUE THREAD

**Issue by abuvaneswari** [meijieru/crnn.pytorch#68]
Hello,

I am using the crnn.pth model from your link: https://www.dropbox.com/s/dboqjk20qjkpta3/crnn.pth?dl=0 
Can you please share what the training data set was for this model?

thank you,
Buvana

**Comment by meijieru** [comment]
It was synthesized by specifial engine.

**Comment by abuvaneswari** [comment]
Thank you. Is this the synthesized dataset by Jaderberg, et. al that the original paper refers to?
Did you use a lexicon during training? What is the length of the lexicon?

**Comment by meijieru** [comment]
1. It's an internal synthesizer.
2. No
3. None
