### ISSUE TITLE
How to use the newly trained model?

### ISSUE THREAD

**Issue by wujiabin8894** [meijieru/crnn.pytorch#75]
@meijieru 
hi, thanks a lot for sharing this project. I followed your README, and got quite a few .pth files in my expr directory. But when I tried to use those to do prediction, I got  error message "KeyError: 'unexpected key "module.cnn.conv0.weight" in state_dict'". Don't know where things got wrong. I just simply modified the model_path in demo.py to one of the .pth file in my expr directory. And run the demo.py .I'm new to machine learning. Can you help me out? thx

**Comment by meijieru** [comment]
Thanks to @liuhu-bigeye for solving this problem

```
If you run crnn = torch.nn.DataParallel(crnn, device_ids=range(opt.ngpu)) in crnn_main.py before saving models during training, just do the same before model.load_state_dict(torch.load(model_path)) in your test.py

model = crnn.CRNN(32, 1, 37, 256)
if torch.cuda.is_available():
    model = model.cuda()
    model = torch.nn.DataParallel(model, device_ids=range(1))

print('loading pretrained model from %s' % model_path)
model.load_state_dict(torch.load(model_path))
```

**Comment by wujiabin8894** [comment]
thanks a lot @meijieru
