### ISSUE TITLE
Getting this error on Anaconda Python

### ISSUE THREAD

**Issue by arsalan993** [meijieru/crnn.pytorch#80]
I installed all the dependencies via Anaconda and now getting this error

(myroot3) arslan993@ubuntu:~/Desktop/crnn.pytorch$ python3 demo.py 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import torch
  File "/home/arslan993/.conda/envs/myroot3/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/arslan993/.conda/envs/myroot3/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN4thpp10THCSTensorIlEC1EP8THCStateP14THCSLongTensor

**Comment by meijieru** [comment]
It seems to be a problem of pytorch.

**Comment by arsalan993** [comment]
Ca you update it to latest pytorch version
