### ISSUE TITLE
Python and Pytorch version

### ISSUE THREAD

**Issue by arsalan993** [meijieru/crnn.pytorch#81]
Can u please upload the requirement.txt file with version or atlease let me know which ubuntu version, python version,  cuda version and pytorch version you are using

**Comment by meijieru** [comment]
It's tested on ubuntu 14.04, python 3.6, pytorch 0.2 .

**Comment by arsalan993** [comment]
on how many fonts it has being trained ..  currently when it on images that a little bit blurred the result are somewhat incorrect ..

**Comment by meijieru** [comment]
You may propose an issue at origin repository.
Since your main concern is solved, I close this issue.
