### ISSUE TITLE
Test Run on images with low resolution and low Quality

### ISSUE THREAD

**Issue by arsalan993** [meijieru/crnn.pytorch#82]
I had a chance to run you code on images with low resolution and a bit low quality but quite readable. 
So code failed in correctly recognizing the text specially when it comes to recognizing the numbers .
But when i increase the resolution by about 25% and increase the quality as well (image with low noice and distortion) it works quite well. 
Can u please tell my the limit to resolution and any technique to increase Quality?

**Comment by meijieru** [comment]
Of course it would bias to the training set, so you could introduce image with low resolution at training stage by data augmentation or others.

By the way, this kind of thing should not be here. You may directly email to the author.
