### ISSUE TITLE
how can I bind warp-ctc to pytorch?

### ISSUE THREAD

**Issue by LiangHao92** [meijieru/crnn.pytorch#83]
In my wapr-ctc folder, there is not a folder named "pytorch_binding", just only a folder named "torch_binding", so, how can I bind warp-ctc to pytorch?

**Comment by Aurora11111** [comment]
I meet the same problem :+1: when I install it ,I also meet:
  Could not find a version that satisfies the requirement warpctx_pytorch (from versions: )
No matching distribution found for warpctx_pytorch
