### ISSUE TITLE
AssertionError: the height of conv must be 1

### ISSUE THREAD

**Issue by gachiemchiep** [meijieru/crnn.pytorch#84]
Hello meijieru. 
At first thank you for your code.

Secondly, i am having this error.

     assert h == 1, "the height of conv must be 1"
     AssertionError: the height of conv must be 1

I successfully create synth-text data and put it into and lmdb using code from https://github.com/bgshih/crnn 

And the size of the image to 300x32 , i tried with 300x32 but it is the same.
I try to print some output

            conv = self.cnn(input)
            print(input.size())
            b, c, h, w = conv.size()
            print(conv.size())

But the output does not help at all

    (64L, 1L, 64L, 600L)
    (64L, 512L, 3L, 151L)

Please help me

**Comment by meijieru** [comment]
Version of PyTorch?

**Comment by gachiemchiep** [comment]
@meijieru 

The detail is as follow :

    pip freeze | grep torch
    torch==0.4.0a0+e2c75d3
    torchvision==0.2.0
    warpctc-pytorch==0.1

**Comment by meijieru** [comment]
Does this happen when run demo?

**Comment by gachiemchiep** [comment]
@meijieru 
No it didn't. I can run the demo.py script file. 
The above error happen when i try to run the training script

**Comment by jetjodh** [comment]
@gachiemchiep Did you solve this problem?

**Comment by gachiemchiep** [comment]
@jetjodh 

I solved this problem by change the image size into 100x32.
300x32 size will mess up the output size so that error happened.

**Comment by jetjodh** [comment]
What method did you apply to change the size? Did you use the dataset.py script or your own?

**Comment by gachiemchiep** [comment]
@jetjodh 
By default the size of training image is 100x32. So for each image i resize it into 100x32 by my own scripts.
