### ISSUE TITLE
torch to pytorch: KeyError: 'b'

### ISSUE THREAD

**Issue by SylviaHolic** [meijieru/crnn.pytorch#85]
When I use tool/convert_t7.py to convert my t7 model finetuned on crnn_demo.t7, I can't convert the t7 model into pytorch model. The format of t7 model is the same as the original crnn in torch version
here: https://github.com/bgshih/crnn. There may be differences between your t7 model and public t7 model.
Can you provide the t7 model suitable for tool/convert_t7.py?

The error is as follow:
Traceback (most recent call last):
  File "tool/convert_t7.py", line 172, in <module>
    torch_to_pytorch(py_model, args.model_file, args.output)
  File "tool/convert_t7.py", line 135, in torch_to_pytorch
    if layer_map[t7_name] != py_name:
KeyError: 'b'

**Comment by meijieru** [comment]
#32
