### ISSUE TITLE
Can I use any img_w in this crnn?

### ISSUE THREAD

**Issue by zoe218** [meijieru/crnn.pytorch#86]
what should I do if I don't want to fix the width of the picture? eh.. I don't know if I express clearly

**Comment by meijieru** [comment]
#54 duplicate

**Comment by zoe218** [comment]
I added the --keep_ratio. But, the test_dataset just be resized by **test_dataset = dataset.lmdbDataset(root = valtoot, transform = dataset.resizeNormalize((100,32))**.  Sorry, I'm still confused:(
