### ISSUE TITLE
AttributeError: 'module' object has no attribute 'gpu_ctc'

### ISSUE THREAD

**Issue by cbzeng110** [meijieru/crnn.pytorch#89]
when I run the crnn_main.py,  the error "AttributeError: 'module' object has no attribute 'gpu_ctc'" occured.
 I have installed PyTorch binding for WarpCTC followint the instruction of https://github.com/SeanNaren/warp-ctc/tree/pytorch_bindings/pytorch_binding. 

Could someone help me solve this problem?@meijieru

**Comment by meijieru** [comment]
#36 duplicate
