### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'data_parallel' when running python demo.py

### ISSUE THREAD

**Issue by ahmedmazari** [meijieru/crnn.pytorch#9]
Hello, 
l'm getting this error when running python `demo.py`.
What's wrong with my the code. It seems that crnn.py don't import the utils which is in  crnn.pytorch/models/ and import the one which is located in crnn.pytorch/

```
 python3.5 demo.py 
loading pretrained model from ./data/crnn.pth
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    preds = model(image)
  File "/home/ahmed/anaconda3/envs/my_env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ahmed/Downloads/crnn.pytorch-master/models/crnn.py", line 78, in forward
    conv = utils.data_parallel(self.cnn, input, self.ngpu)
AttributeError: module 'utils' has no attribute 'data_parallel'

```

**Comment by meijieru** [comment]
I do not meet this problem.
Where did you run this program?

**Comment by ahmedmazari** [comment]
in my laptop with python 3.5 ,  torch.__version__ '0.1.12_2', cuda 8.0 and cudnn 5.1

**Comment by ahmedmazari** [comment]
@meijieru , what's wrong around here ?

**Comment by ahmedmazari** [comment]
@meijieru  problem solved with the code proposed by @ daobilige-su in https://github.com/meijieru/crnn.pytorch/issues/1

**Comment by meijieru** [comment]
I could not reproduce this problem.
Since it is OK for you to run demo, I just this issue temporarily.

**Comment by grkashani** [comment]
copy utils.py from here  to your directory 
https://github.com/grkashani/utils-stanford/blob/master/utils.py
