### ISSUE TITLE
how to make dataset

### ISSUE THREAD

**Issue by MingChaoXu** [meijieru/crnn.pytorch#91]
i want to train crnn by myself. it says Construct dataset following origin guide. but i don't understand where is the origin guide?

**Comment by meijieru** [comment]
That means origin crnn implementation

**Comment by MingChaoXu** [comment]
thanks, i think i can solve it

**Comment by arsalan993** [comment]
@MingChaoXu can you please explain the procedure of how to prepare my own data set and which steps i should follow to train my own dataset

**Comment by MingChaoXu** [comment]
@arsalan993 here is the link https://github.com/bgshih/crnn , use the file create_dataset.py, there is a function in it. you should have the route of test/val/train dataset, you can write a script to achieve them, then run this function, and finished
